### ISSUE TITLE
setContentMargins闪烁问题，看来是没办法很好解决了

### ISSUE THREAD

**Issue by xoxoj** [Bringer-of-Light/Qt-Nice-Frameless-Window#1]
我之前也写了一套qt frameless的解决方案，但是setContentMargins闪烁问题没办法解决，后来被否了。

**Comment by Bringer-of-Light** [comment]
@xoxoj 已经解决，只需要在 setContentMargins 后，使用 repaint()

**Comment by wangwenx190** [comment]
@Bringer-of-Light 厉害！
