### ISSUE TITLE
缺少#include <GdiPlusColor.h>，应该如何配置？

### ISSUE THREAD

**Issue by jackHuanghello** [Bringer-of-Light/Qt-Nice-Frameless-Window#13]
导入了framelesswindow.cpp文件之后发现缺少了<GdiPlusColor.h>，我下载了一个GDIPLUS文件，里面有一个include文件夹（包含了<GdiPlusColor.h>和很多其他的头文件）和一个lib文件夹（里面有一个GdiPlus.lib文件）请问有人清楚应该如何配置吗，是在visual studio中配置吗，还是通过Qt？我装的是visual studio 2017， Qt版本也是5.9.2。

**Comment by Bringer-of-Light** [comment]
是编译时找不到 GdiPlusColor.h 吗？请问是什么操作系统？安装windows SDK 应该可以解决

**Comment by gloryfya** [comment]
改成
`#include <gdiplus/GdiPlusColor.h>`
