### ISSUE TITLE
qt5下不能移动窗口,刷新也有问题

### ISSUE THREAD

**Issue by spchziee** [Bringer-of-Light/Qt-Nice-Frameless-Window#14]
这版本是QT4的么,QT5下没有setWindowFlag,改成setWindowFlags就出现了上面的问题

**Comment by Bringer-of-Light** [comment]
Qt5.7和Qt5.9没有问题，你的Qt5是5.几？

**Comment by Bringer-of-Light** [comment]
@spchziee 请看说明文档和exampleforwindows

**Comment by spchziee** [comment]
5.7  我只是运行了exampleforwindows  ,最奇怪的是为什么没有setWindowFlag  只有setWindowFlags

![1](https://user-images.githubusercontent.com/7788346/38660848-57346364-3e61-11e8-9e0c-fb61e56ebc1f.png)

**Comment by Bringer-of-Light** [comment]
@spchziee 不好意思，这个函数时Qt5.9才有的，我会更新一下这个代码改成使用setwindowflags

**Comment by Bringer-of-Light** [comment]
@spchziee master分支已经修复此问题，请重新下载尝试
