### ISSUE TITLE
win7+qt5.8.0 + vs2013 按钮失灵

### ISSUE THREAD

**Issue by pele228** [Bringer-of-Light/Qt-Nice-Frameless-Window#16]
你好, 在该配置环境下， 最小化和最大化，退出按钮没有作用，点击的时候会闪现出默认的最小，最大化图标.

**Comment by blueany** [comment]
我也是这个问题，win7_sp1_32 + qt5.11.2+vs2015，开启Areo， 出现系统默认的关闭和最大化按钮
