### ISSUE TITLE
显示系统默认的最小，最大，退出按钮

### ISSUE THREAD

**Issue by pele228** [Bringer-of-Light/Qt-Nice-Frameless-Window#17]
你好，win7+qt5.8.0 +vs2013条件下， 按照两种载入方式， 鼠标放在右上角时都会出现系统默认的最小，最大，和退出图标. 请问是什么原因

**Comment by Bringer-of-Light** [comment]
在CFramelessWindow的构造函数里，去掉这个 flag：
Qt::WindowSystemMenuHint
