### ISSUE TITLE
窗口内有OpenGLWidget时的问题

### ISSUE THREAD

**Issue by Protostars** [Bringer-of-Light/Qt-Nice-Frameless-Window#19]
窗口内存在OpenGLWidget时，标题栏显示位置出现错误

**Comment by iamsurka** [comment]
是Intel驱动在OpenGL实现上的bug。可将OpenGL窗口嵌入到一个普通的窗口内绕过该问题（需要借助HTTRANSPARENT）。

**Comment by vtronko** [comment]
@iamsurka do you have a working example?
