### ISSUE TITLE
我已经把我fork的仓库删除了

### ISSUE THREAD

**Issue by wangwenx190** [Bringer-of-Light/Qt-Nice-Frameless-Window#3]
您现在这个版本的代码仓库已经比我自己那个修改版的完善很多了，与其继续修补我那个定制版，还不如直接用您的来得划算，所以我就把我那个fork来的仓库删了，决定直接用您这个仓库。LICENSE我会保留的，您放心。

**Comment by Bringer-of-Light** [comment]
@wangwenx190
好的，很高兴能帮助到您
