### ISSUE TITLE
system min/max/close button show on Windows 7 when click custom title bar

### ISSUE THREAD

**Issue by slackzh** [Bringer-of-Light/Qt-Nice-Frameless-Window#42]
![11](https://user-images.githubusercontent.com/6254237/76705303-05108200-671a-11ea-9bfa-5ca154d1b723.gif)

tried below compilers, this issue is always ocurr

- msvc 2015 32bit+Qt 5.9.8
- msvc 2017 32bit+Qt 5.12.4  
- msvc 2017 64bit+Qt 5.12.4

**Comment by douzhongqiang** [comment]
you can see closed issues #25 and #17
